name: Debug with tmate

on:
  workflow_dispatch:

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true  # Only repo owner can connect
