name: Debug with Tmate

on:
  workflow_dispatch:

jobs:
  debug:
    name: Tmate Debug Session
    runs-on: ubuntu-latest
    steps:
      - name: Install Tmate & SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-client openssh-server tmate

      - name: Set up SSH Key (Optional)
        run: |
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/id_rsa

      - name: Start Tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Keep alive for 2 hours (max timeout)
        run: sleep 7200
